### ISSUE TITLE
请问老师G、E、H系数矩阵如何获取

### ISSUE THREAD

**Issue by sometimesstudy** [a280558071/CCG-Algorithm-for-TwoStageRobustOptimization#1]

**Comment by a280558071** [comment]
这些系数矩阵因问题建模不同而不同



---- 回复的原邮件 ----
| 发件人 | Yuxuan ***@***.***> |
| 日期 | 2023年02月15日 21:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [a280558071/CCG-Algorithm-for-TwoStageRobustOptimization] 请问老师G、E、H系数矩阵如何获取 (Issue #1) |
